version: '3'

services:
  frontendui:
    build: UI
    ports:
      - 8501:8501
    volumes:
      - './UI:/app:delegated'
    depends_on:
      - service

  training:
    build: training
    depends_on:
      - mlflow
#    entrypoint: [ "prefect", "orion", "start" ]
    environment:
      - PREFECT_ORION_API_HOST=0.0.0.0
    ports:
      - 4200:4200
    volumes:
      - data:/mlruns

  service:
    build: service
    ports:
      - 8000:8000

  mlflow:
    build: mlflow
    ports:
      - 5000:5000
    volumes:
      - data:/mlflow
    environment:
      BACKEND_URI: sqlite:////mlflow/mlflow.db
      ARTIFACT_ROOT: /mlflow/artifacts

#  lab:
#    build:
#        context: jupyter
#        dockerfile: Dockerfile
#        # environment:
#    ports:
#        - "8888:8888"
#    tty: true
#    command:
#        jupyter lab
#            --ip=0.0.0.0
#            --allow-root
#            --no-browser
#            --NotebookApp.token=''
#            --NotebookApp.notebook_dir='/notebooks'
#    volumes:
#            - ./data:/notebooks
volumes:
  data: