version: '3'

services:
  frontendui:
    build: UI
    ports:
      - 8501:8501
    volumes:
      - './UI:/app:delegated'
    depends_on:
      - service

  train:
    build: training
    depends_on:
      - mlflow
#    entrypoint: [ "prefect", "orion", "start" ]
    environment:
      - PREFECT_ORION_API_HOST=0.0.0.0
    ports:
      - 4200:4200
    volumes:
      - models:/mlruns

  service:
    build: service
    ports:
      - 8000:8000

  mlflow:
    build: mlflow
    ports:
      - 5000:5000
    volumes:
      - models:/mlruns

volumes:
  models: