version: '3'

services:
  frontendui:
    build: UI
    ports:
      - 8501:8501
    volumes:
      - data:/model
    depends_on:
      - service

  training:
    build: training
    depends_on:
      - mlflow
#    entrypoint: [ "prefect", "orion", "start" ]
    environment:
      - PREFECT_ORION_API_HOST=0.0.0.0
    ports:
      - 4200:4200
    volumes:
      - data:/mlruns
      - ${ARTIFACT_PATH}:${ARTIFACT_PATH}

  service:
    build: service
    ports:
      - 8000:8000
    depends_on:
      - mlflow
    volumes:
      - ${ARTIFACT_PATH}:${ARTIFACT_PATH}
      - data:/app/model

  mlflow:
    build: mlflow
    container_name: mlflow
    ports:
      - ${MLFLOW_PORT}:${MLFLOW_PORT}

    volumes:
      - ${ARTIFACT_PATH}:${ARTIFACT_PATH}
      - data:/mlflow
    environment:
      DB_URI: sqlite:////mlflow/mlflow.db
      VIRTUAL_HOST: ${HOST}
      VIRTUAL_PORT: ${MLFLOW_PORT}
      ARTIFACT_PATH: ${ARTIFACT_PATH}
    command: ./start.sh


  lab:
    build:
        context: jupyter
        dockerfile: Dockerfile
        # environment:
    ports:
        - "8888:8888"
    tty: true
    command:
        jupyter lab
            --ip=0.0.0.0
            --allow-root
            --no-browser
            --NotebookApp.token=''
            --NotebookApp.notebook_dir='/notebooks'
    volumes:
            - ./data:/notebooks
            - ${ARTIFACT_PATH}:${ARTIFACT_PATH}
volumes:
  data: